{{- if .Values.certificates.clusterIssuer.enabled -}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: fleetconfig-controller
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
spec:
  {{ .Values.certificates.clusterIssuer.spec | toYaml | indent 2 }}
{{- end -}}